In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

###   DIABETES

In [3]:
df = pd.read_csv('diabetes.csv')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2,138,62,35,0,33.6,0.127,47,1
1,0,84,82,31,125,38.2,0.233,23,0
2,0,145,0,0,0,44.2,0.630,31,1
3,0,135,68,42,250,42.3,0.365,24,1
4,1,139,62,41,480,40.7,0.536,21,0
...,...,...,...,...,...,...,...,...,...
1995,2,75,64,24,55,29.7,0.370,33,0
1996,8,179,72,42,130,32.7,0.719,36,1
1997,6,85,78,0,0,31.2,0.382,42,0
1998,0,129,110,46,130,67.1,0.319,26,1
1999,2,81,72,15,76,30.1,0.547,25,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               2000 non-null   int64
 1   Glucose                   2000 non-null   int64
 2   BloodPressure             2000 non-null   int64
 3   SkinThickness             2000 non-null   int64
 4   Insulin                   2000 non-null   int64
 5   BMI                       2000 non-null   float64
 6   DiabetesPedigreeFunction  2000 non-null   float64
 7   Age                       2000 non-null   int64
 8   Outcome                   2000 non-null   int64
dtypes: float64(2), int64(7)
memory usage: 140.8 KB

In [5]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,3.703500,121.182500,69.145500,20.935000,80.254000,32.193000,0.470930,33.090500,0.342000
std,3.306063,32.068636,19.188315,16.103243,111.180534,8.149901,0.323553,11.786423,0.474498
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,63.500000,0.000000,0.000000,27.375000,0.244000,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,40.000000,32.300000,0.376000,29.000000,0.000000
75%,6.000000,141.000000,80.000000,32.000000,130.000000,36.800000,0.624000,40.000000,1.000000
max,17.000000,199.000000,122.000000,110.000000,744.000000,80.600000,2.420000,81.000000,1.000000

In [6]:
df.isnull().any()

Pregnancies                 False
Glucose                     False
BloodPressure               False
SkinThickness               False
Insulin                     False
BMI                         False
DiabetesPedigreeFunction    False
Age                         False
Outcome                     False
dtype: bool

In [7]:
X = df[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin','BMI', 'DiabetesPedigreeFunction', 'Age']]
y = df['Outcome']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [9]:
model=LogisticRegression()

In [10]:
model.fit(X_train,y_train)

C:\anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [11]:
y_pred = model.predict(X_test)

In [12]:
acc = accuracy_score(y_test,y_pred)
acc

0.805

In [13]:
model1 = GaussianNB()
model1.fit(X_train,y_train)
y_pred = model1.predict(X_test)
acc = accuracy_score(y_test,y_pred)
acc

0.795

In [14]:
model2 = SVC()
model2.fit(X_train,y_train)
y_pred = model2.predict(X_test)
acc = accuracy_score(y_test,y_pred)
acc

0.7883333333333333

In [15]:
model3 = DecisionTreeClassifier()
model3.fit(X_train,y_train)
y_pred = model3.predict(X_test)
acc = accuracy_score(y_test,y_pred)
acc

0.9566666666666667

In [16]:
model4 = KNeighborsClassifier()
model4.fit(X_train,y_train)
y_pred = model4.predict(X_test)
acc = accuracy_score(y_test,y_pred)
acc

0.7716666666666666

### Heart

In [17]:
df = pd.read_csv('heart.csv')
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [19]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [20]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [21]:
X = df[['age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal']]
y = df['target']

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [23]:
model10=LogisticRegression()
model10.fit(X_train,y_train)
y_pred = model10.predict(X_test)
acc = accuracy_score(y_test,y_pred)
acc

C:\anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.8131868131868132

In [24]:
model11 = GaussianNB()
model11.fit(X_train,y_train)
y_pred = model11.predict(X_test)
acc = accuracy_score(y_test,y_pred)
acc

0.8351648351648352

In [25]:
model22 = SVC()
model22.fit(X_train,y_train)
y_pred = model22.predict(X_test)
acc = accuracy_score(y_test,y_pred)
acc

0.7032967032967034

In [26]:
model33 = DecisionTreeClassifier()
model33.fit(X_train,y_train)
y_pred = model33.predict(X_test)
acc = accuracy_score(y_test,y_pred)
acc

0.7362637362637363

In [27]:
model44 = KNeighborsClassifier()
model44.fit(X_train,y_train)
y_pred = model44.predict(X_test)
acc = accuracy_score(y_test,y_pred)
acc

0.6593406593406593

### cross

In [28]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(),X,y,cv=5)

array([0.60655738, 0.60655738, 0.73770492, 0.68333333, 0.58333333])

In [29]:
cross_val_score(SVC(C=10,gamma="auto",kernel="linear"),X,y,cv=5)

array([0.7704918 , 0.91803279, 0.7704918 , 0.86666667, 0.76666667])

## Grid Search CV

In [30]:
from sklearn.model_selection import GridSearchCV
gs = GridSearchCV(SVC(),
                 {
                     'C':[1,2,5,9,10],
                     'kernel':['rbf','linear'],
                     'gamma':['scale','auto']
                 }, cv=4,return_train_score=False)
gs.fit(X,y)

GridSearchCV(cv=4, estimator=SVC(),
             param_grid={'C': [1, 2, 5, 9, 10], 'gamma': ['scale', 'auto'],
                         'kernel': ['rbf', 'linear']})

In [31]:
gs.cv_results_

{'mean_fit_time': array([3.99583578e-03, 1.22087306e+00, 1.17166042e-02, 1.06616372e+00,
        0.00000000e+00, 1.10219407e+00, 1.34708881e-02, 8.24538112e-01,
        1.24609470e-03, 4.30023724e+00, 1.17166042e-02, 4.27633995e+00,
        0.00000000e+00, 2.95633864e+00, 3.90535593e-03, 2.80655849e+00,
        7.81089067e-03, 3.84039873e+00, 3.90505791e-03, 3.80379748e+00]),
 'std_fit_time': array([2.55143075e-03, 5.23615619e-01, 6.76458462e-03, 6.18406215e-01,
        0.00000000e+00, 6.39933183e-01, 5.11678572e-04, 4.10362238e-01,
        2.15829934e-03, 3.35462577e+00, 6.76458461e-03, 3.27619421e+00,
        0.00000000e+00, 8.92796644e-01, 6.76427489e-03, 1.43469283e+00,
        7.81089068e-03, 2.02398913e+00, 6.76375870e-03, 1.56193665e+00]),
 'mean_score_time': array([0.01527375, 0.00490123, 0.03124166, 0.        , 0.01562214,
        0.00490481, 0.03166032, 0.00049847, 0.01095533, 0.00781232,
        0.03124207, 0.        , 0.01562124, 0.00781572, 0.01171166,
        0.00390494, 0.02343112, 0.00099742, 0.01171607, 0.        ]),
 'std_score_time': array([5.83208004e-03, 6.40047659e-03, 6.07850494e-07, 0.00000000e+00,
        1.28392334e-06, 6.40191525e-03, 4.22013681e-04, 8.63381678e-04,
        6.73008007e-03, 7.81232139e-03, 1.60268899e-06, 0.00000000e+00,
        7.22667912e-07, 7.81572051e-03, 6.76173075e-03, 6.76355223e-03,
        7.81196373e-03, 1.72758926e-03, 6.76427560e-03, 0.00000000e+00]),
 'param_C': masked_array(data=[1, 1, 1, 1, 2, 2, 2, 2, 5, 5, 5, 5, 9, 9, 9, 9, 10, 10,
                    10, 10],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_gamma': masked_array(data=['scale', 'scale', 'auto', 'auto', 'scale', 'scale',
                    'auto', 'auto', 'scale', 'scale', 'auto', 'auto',
                    'scale', 'scale', 'auto', 'auto', 'scale', 'scale',
                    'auto', 'auto'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 1, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 1, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 1, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 2, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 2, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 2, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 2, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 5, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 5, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 5, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 5, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 9, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 9, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 9, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 9, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 10, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 10, 'gamma': 'auto', 'kernel': 'linear'}],
 'split0_test_score': array([0.60526316, 0.85526316, 0.55263158, 0.85526316, 0.64473684,
        0.85526316, 0.55263158, 0.85526316, 0.63157895, 0.84210526,
        0.55263158, 0.84210526, 0.64473684, 0.81578947, 0.55263158,
        0.81578947, 0.64473684, 0.81578947, 0.55263158, 0.81578947]),
 'split1_test_score': array([0.69736842, 0.88157895, 0.53947368, 0.88157895, 0.71052632,
        0.88157895, 0.53947368, 0.88157895, 0.72368421, 0.86842105,
        0.53947368, 0.86842105, 0.72368421, 0.85526316, 0.53947368,
        0.85526316, 0.72368421, 0.85526316, 0.53947368, 0.85526316]),
 'split2_test_score': array([0.64473684, 0.85526316, 0.53947368, 0.85526316, 0.67105263,
        0.85526316, 0.53947368, 0.85526316, 0.67105263, 0.84210526,
        0.53947368, 0.84210526, 0.68421053, 0.82894737, 0.53947368,
        0.82894737, 0.68421053, 0.82894737, 0.53947368, 0.82894737]),
 'split3_test_score': array([0.65333333, 0.77333333, 0.54666667, 0.77333333, 0.65333333,
        0.8       , 0.56      , 0.8       , 0.65333333, 0.81333333,
        0.56      , 0.81333333, 0.65333333, 0.81333333, 0.56      ,
        0.81333333, 0.68      , 0.81333333, 0.56      , 0.81333333]),
 'mean_test_score': array([0.65017544, 0.84135965, 0.5445614 , 0.84135965, 0.66991228,
        0.84802632, 0.54789474, 0.84802632, 0.66991228, 0.84149123,
        0.54789474, 0.84149123, 0.67649123, 0.82833333, 0.54789474,
        0.82833333, 0.68315789, 0.82833333, 0.54789474, 0.82833333]),
 'std_test_score': array([0.03272553, 0.04071789, 0.00550749, 0.04071789, 0.02529557,
        0.02973655, 0.00881481, 0.02973655, 0.03404786, 0.01948613,
        0.00881481, 0.01948613, 0.03094913, 0.01664287, 0.00881481,
        0.01664287, 0.02797159, 0.01664287, 0.00881481, 0.01664287]),
 'rank_test_score': array([15,  5, 20,  5, 13,  1, 16,  1, 13,  3, 16,  3, 12,  7, 16,  7, 11,
         7, 16,  7])}

In [32]:
df1 = pd.DataFrame(gs.cv_results_)
df1

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003996,0.002551,0.015274,5.832080e-03,1,scale,rbf,"{'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}",0.605263,0.697368,0.644737,0.653333,0.650175,0.032726,15
1,1.220873,0.523616,0.004901,6.400477e-03,1,scale,linear,"{'C': 1, 'gamma': 'scale', 'kernel': 'linear'}",0.855263,0.881579,0.855263,0.773333,0.841360,0.040718,5
2,0.011717,0.006765,0.031242,6.078505e-07,1,auto,rbf,"{'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}",0.552632,0.539474,0.539474,0.546667,0.544561,0.005507,20
3,1.066164,0.618406,0.000000,0.000000e+00,1,auto,linear,"{'C': 1, 'gamma': 'auto', 'kernel': 'linear'}",0.855263,0.881579,0.855263,0.773333,0.841360,0.040718,5
4,0.000000,0.000000,0.015622,1.283923e-06,2,scale,rbf,"{'C': 2, 'gamma': 'scale', 'kernel': 'rbf'}",0.644737,0.710526,0.671053,0.653333,0.669912,0.025296,13
5,1.102194,0.639933,0.004905,6.401915e-03,2,scale,linear,"{'C': 2, 'gamma': 'scale', 'kernel': 'linear'}",0.855263,0.881579,0.855263,0.800000,0.848026,0.029737,1
6,0.013471,0.000512,0.031660,4.220137e-04,2,auto,rbf,"{'C': 2, 'gamma': 'auto', 'kernel': 'rbf'}",0.552632,0.539474,0.539474,0.560000,0.547895,0.008815,16
7,0.824538,0.410362,0.000498,8.633817e-04,2,auto,linear,"{'C': 2, 'gamma': 'auto', 'kernel': 'linear'}",0.855263,0.881579,0.855263,0.800000,0.848026,0.029737,1
8,0.001246,0.002158,0.010955,6.730080e-03,5,scale,rbf,"{'C': 5, 'gamma': 'scale', 'kernel': 'rbf'}",0.631579,0.723684,0.671053,0.653333,0.669912,0.034048,13
9,4.300237,3.354626,0.007812,7.812321e-03,5,scale,linear,"{'C': 5, 'gamma': 'scale', 'kernel': 'linear'}",0.842105,0.868421,0.842105,0.813333,0.841491,0.019486,3
10,0.011717,0.006765,0.031242,1.602689e-06,5,auto,rbf,"{'C': 5, 'gamma': 'auto', 'kernel': 'rbf'}",0.552632,0.539474,0.539474,0.560000,0.547895,0.008815,16
11,4.276340,3.276194,0.000000,0.000000e+00,5,auto,linear,"{'C': 5, 'gamma': 'auto', 'kernel': 'linear'}",0.842105,0.868421,0.842105,0.813333,0.841491,0.019486,3
12,0.000000,0.000000,0.015621,7.226679e-07,9,scale,rbf,"{'C': 9, 'gamma': 'scale', 'kernel': 'rbf'}",0.644737,0.723684,0.684211,0.653333,0.676491,0.030949,12
13,2.956339,0.892797,0.007816,7.815721e-03,9,scale,linear,"{'C': 9, 'gamma': 'scale', 'kernel': 'linear'}",0.815789,0.855263,0.828947,0.813333,0.828333,0.016643,7
14,0.003905,0.006764,0.011712,6.761731e-03,9,auto,rbf,"{'C': 9, 'gamma': 'auto', 'kernel': 'rbf'}",0.552632,0.539474,0.539474,0.560000,0.547895,0.008815,16
15,2.806558,1.434693,0.003905,6.763552e-03,9,auto,linear,"{'C': 9, 'gamma': 'auto', 'kernel': 'linear'}",0.815789,0.855263,0.828947,0.813333,0.828333,0.016643,7
16,0.007811,0.007811,0.023431,7.811964e-03,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.644737,0.723684,0.684211,0.680000,0.683158,0.027972,11
17,3.840399,2.023989,0.000997,1.727589e-03,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.815789,0.855263,0.828947,0.813333,0.828333,0.016643,7
18,0.003905,0.006764,0.011716,6.764276e-03,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.552632,0.539474,0.539474,0.560000,0.547895,0.008815,16
19,3.803797,1.561937,0.000000,0.000000e+00,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.815789,0.855263,0.828947,0.813333,0.828333,0.016643,7

In [33]:
df1[['param_C','param_gamma','param_kernel','mean_test_score']]

   param_C param_gamma param_kernel  mean_test_score
0        1       scale          rbf         0.650175
1        1       scale       linear         0.841360
2        1        auto          rbf         0.544561
3        1        auto       linear         0.841360
4        2       scale          rbf         0.669912
5        2       scale       linear         0.848026
6        2        auto          rbf         0.547895
7        2        auto       linear         0.848026
8        5       scale          rbf         0.669912
9        5       scale       linear         0.841491
10       5        auto          rbf         0.547895
11       5        auto       linear         0.841491
12       9       scale          rbf         0.676491
13       9       scale       linear         0.828333
14       9        auto          rbf         0.547895
15       9        auto       linear         0.828333
16      10       scale          rbf         0.683158
17      10       scale       linear         0.828333
18      10        auto          rbf         0.547895
19      10        auto       linear         0.828333

In [34]:
gs.best_params_

{'C': 2, 'gamma': 'scale', 'kernel': 'linear'}

In [35]:
gs.best_score_

0.8480263157894736

###
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import GridSearchCV
gs = GridSearchCV(SVC(),
                 {
                     'C':[1,2,5,9,10],
                     'kernel':['rbf','linear'],
                     'gamma':['scale','auto']
                 }, cv=4,return_train_score=False)
gs.fit(X,y)

gs.cv_results_
df1 = pd.DataFrame(gs.cv_results_)
df1
df1[['param_C','param_gamma','param_kernel','mean_test_score']]
gs.best_params_
gs.best_score_

## Random-Search-CV

In [36]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
rs = RandomizedSearchCV(SVC(),
                 {
                     'C':[1,2,5,9,10],
                     'kernel':['rbf','poly'],
                     'gamma':['scale','auto']
                 }, cv=4,return_train_score=True,n_iter=3)
rs.fit(X,y)

In [ ]:
rs.cv_results_

In [ ]:
df2 = pd.DataFrame(gs.cv_results_)
df2

In [ ]:
df2[['param_C','param_gamma','param_kernel','mean_test_score']]
#gs.best_params_
#gs.best_score_

In [ ]:
#df1[['param_C','param_gamma','param_kernel','mean_test_score']]
gs.best_params_
#gs.best_score_

In [ ]:
#df1[['param_C','param_gamma','param_kernel','mean_test_score']]
#gs.best_params_
gs.best_score_